version: '3.9'

services:

  database:
    image: postgres:alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: defaultdnsupdaterpassword
      POSTGRES_USER: dnsupdater
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
