// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using record_service.infrastructures.databases;

#nullable disable

namespace record_service.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250123144442_domain_key")]
    partial class domain_key
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("record_service.models.RecordModel", b =>
                {
                    b.Property<string>("domain")
                        .HasColumnType("text");

                    b.Property<string>("encryptedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("domain");

                    b.ToTable("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
